name: Cypress

on: [pull_request]

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Node.JS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Set Tokens
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM }} && npm config set @gsap:registry https://npm.greensock.com/ && npm config set //npm.greensock.com/:_authToken ${{ secrets.GSAP }}

      - name: Install Pnpm
        run: sudo npm -g i pnpm

      - name: Get pnpm cache directory path
        id: pnpm-cache
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Set up Cypress binary cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install Node Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Cypress.io
        uses: cypress-io/github-action@v6
        with:
          install-command: pnpm install
          config-file: cypress.config.ts
          component: true
          browser: electron
          headed: false
        env:
          NODE_ENV: test

      - name: Merge Cypress Reports
        run: npx mochawesome-merge ./cypress/reports/mocha*.json > ./cypress/reports/index.json

      - name: Cypress report action
        uses: dmitry/cypress-report-action@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          pathname: cypress/reports/index.json