name: Cypress

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cypress.io
      uses: cypress-io/github-action@v2.9.7
      with:
        config-file: cypress.json
        browser: chrome
        command: pnpm run test
        install: true
        install-command: npm -g i pnpm && pnpm i
        headless: true
    - name: Cypress report action
      uses: dmitry/cypress-report-action@1.0.0
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        pathname: cypress/reports/html/index.json