name: Check Types

on: [pull_request]

jobs:
  typescript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Node.JS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Pnpm
        run: sudo npm -g i pnpm

      - name: Get pnpm cache directory path
        id: pnpm-cache
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Set Tokens
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM }} && npm config set @gsap:registry https://npm.greensock.com/ && npm config set //npm.greensock.com/:_authToken ${{ secrets.GSAP }}
        env:
          CI: TRUE

      - name: Install Node Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Test Typescript types
        run: pnpm run check:types
